src/OC/PlatformBundle/Entity/Image.php
<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Image
 *
 * @ORM\Table(name="oc_image")
 * @ORM\Entity(repositoryClass="OC\PlatformBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    // Sans annotation car ne sera pas persister en BDD, ne sert pas a doctrine
    /**
     * @Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"image/png", "image/jpg", "image/jpeg"},
     *     mimeTypesMessage = "Merci d'ajouter une image en .jpg, .jpeg ou .png",
     *     maxSizeMessage = "Le fichier est trop lourd. Taille maximum autorisée: 1024k"
     * )
     */
    private $file;

    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;

    public function getFile()
    {
        return $this->file;
    }

    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
        // On sauvegarde l'extension du fichier pour le supprimer plus tard
        $this->tempFilename = $this->url;

        // On réinitialise les valeurs des attributs url et alt
        $this->url = null;
        $this->alt = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
        return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
        return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
        $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
        if (file_exists($oldFile)) {
            unlink($oldFile);
        }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
        $this->getUploadRootDir(), // Le répertoire de destination
        $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
        // On supprime le fichier
        unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
}

src/OC/PlatformBundle/Form/AdvertType.php
<?php

namespace OC\PlatformBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class AdvertType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('date',           DateType::class)
        ->add('title',          TextType::class)
        ->add('author',         TextType::class)
        ->add('authorEmail',    EmailType::class)
        ->add('content',        TextareaType::class)
        ->add('image',          ImageType::class)
        ->add('categories', EntityType::class, array(
            'class'        => 'OCPlatformBundle:Category',
            'choice_label' => 'name',
            'multiple'     => true,
            'expanded'     => true,
        ))
        ->add('save',           SubmitType::class);

        // On ajoute une fonction qui va écouter un évènement
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,    // 1er argument : L'évènement qui nous intéresse : ici, PRE_SET_DATA
            function(FormEvent $event) { // 2e argument : La fonction à exécuter lorsque l'évènement est déclenché
            // On récupère notre objet Advert sous-jacent
            $advert = $event->getData();
    
            // Cette condition est importante, on en reparle plus loin
            if (null === $advert) {
                return; // On sort de la fonction sans rien faire lorsque $advert vaut null
            }
    
            // Si l'annonce n'est pas publiée, ou si elle n'existe pas encore en base (id est null)
            if (!$advert->getPublished() || null === $advert->getId()) {
                // Alors on ajoute le champ published
                $event->getForm()->add('published', CheckboxType::class, array('required' => false, 'label' => 'Publier'));
            } else {
                // Sinon, on le supprime
                $event->getForm()->remove('published');
            }
            }
        );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'OC\PlatformBundle\Entity\Advert'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'oc_platformbundle_advert';
    }


}

src/OC/PlatformBundle/Controller/AdvertController.php
<?php

// src/OC/PlatformBundle/Controller/AdvertController.php

namespace OC\PlatformBundle\Controller;

use OC\PlatformBundle\Entity\Advert;
use OC\PlatformBundle\Entity\Image;
use OC\PlatformBundle\Entity\Application;
use OC\PlatformBundle\Entity\AdvertSkill;
use OC\PlatformBundle\Form\AdvertType;
use OC\PlatformBundle\Form\AdvertEditType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class AdvertController extends Controller
{
    public function indexAction($page)
    {
        if ($page < 1) {
            throw new NotFoundHttpException('Page "'.$page.'" inexistante.');
        }
        
        $nbPerPage = 3;

        // On récupère notre objet Paginator
        $listAdverts = $this->getDoctrine()
            ->getManager()
            ->getRepository('OCPlatformBundle:Advert')
            ->getAdverts($page, $nbPerPage)
        ;

        // On calcule le nombre total de pages grâce au count($listAdverts) qui retourne le nombre total d'annonces
        $nbPages = ceil(count($listAdverts) / $nbPerPage);

        // Si la page n'existe pas, on retourne une 404
        if ($page > $nbPages) {
        throw $this->createNotFoundException("La page ".$page." n'existe pas.");
        }

        return $this->render('OCPlatformBundle:Advert:index.html.twig', array(
            'listAdverts' => $listAdverts,
            'nbPages'     => $nbPages,
            'page'        => $page,
        ));
        
    }

    public function viewAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);
        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }
    
        return $this->render('OCPlatformBundle:Advert:view.html.twig', array(
            'advert' => $advert
        ));
    }

    /**
    * @Security("has_role('ROLE_AUTEUR')")
    */
    public function addAction(Request $request)
    {
    // On crée un objet Advert
    $advert = new Advert();

    $form = $this->createForm(AdvertType::class, $advert);

    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

        $em = $this->getDoctrine()->getManager();
        $em->persist($advert);
        $em->flush();

        $request->getSession()->getFlashBag()->add('info', 'Annonce bien enregistrée.');

        return $this->redirectToRoute('oc_platform_view', array('id' => $advert->getId()));

    }

    return $this->render('OCPlatformBundle:Advert:add.html.twig', array(
        'form' => $form->createView()
    ));

    }

    public function editAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);
        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }

        $form = $this->createForm(AdvertEditType::class, $advert);

        if ($request->isMethod('POST')) 
        {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($advert);
                $em->flush();

                $request->getSession()->getFlashBag()->add('info', 'Annonce bien modifée.');

                return $this->redirectToRoute('oc_platform_view', array('id' => $advert->getId()));
            }
        }
    
        return $this->render('OCPlatformBundle:Advert:edit.html.twig', array(
        'advert' => $advert,
        'form' => $form->createView()
        ));

    }

    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
    
        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);
    
        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }
    
        // On crée un formulaire vide, qui ne contiendra que le champ CSRF
        // Cela permet de protéger la suppression d'annonce contre cette faille
        $form = $this->get('form.factory')->create();
    
        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em->remove($advert);
            $em->flush();
    
            $request->getSession()->getFlashBag()->add('info', "L'annonce a bien été supprimée.");
    
            return $this->redirectToRoute('oc_platform_home');
        }
        
        return $this->render('OCPlatformBundle:Advert:delete.html.twig', array(
            'advert' => $advert,
            'form'   => $form->createView(),
        ));
    }




    public function menuAction($limit)
    {
        $em = $this->getDoctrine()->getManager();

        $listAdverts = $em->getRepository('OCPlatformBundle:Advert')->findBy(
            array(),                 // Pas de critère
            array('date' => 'desc'), // On trie par date décroissante
            $limit,                  // On sélectionne $limit annonces
            0                        // À partir du premier
        );

        return $this->render('OCPlatformBundle:Advert:menu.html.twig', array(
            'listAdverts' => $listAdverts
        ));
    }
    

    public function allCategoriesAction()
    {
        $repository = $this->getDoctrine()
        ->getManager()
        ->getRepository('OCPlatformBundle:Category')
        ;

        $categories = $repository->findAll();

        return $this->render('OCPlatformBundle:Advert:categories.html.twig', array(
        'categories' => $categories
        ));
    }

    public function editImageAction($advertId)
    {
        $em = $this->getDoctrine()->getManager();

        // On récupère l'annonce
        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($advertId);

        // On modifie l'URL de l'image par exemple
        $advert->getImage()->setUrl('test.png');

        // On n'a pas besoin de persister l'annonce ni l'image.
        // Rappelez-vous, ces entités sont automatiquement persistées car
        // on les a récupérées depuis Doctrine lui-même
        
        // On déclenche la modification
        $em->flush();

        return new Response('OK');
    }

    public function purgeAction(Request $request, $days)
    {
        // On récupère le service
        $purge = $this->container
            ->get('oc_platform.purger.advert')
            ->purge($days);
        
        $request->getSession()->getFlashBag()->add('info', 'Annonces bien purgées.');
        
        return $this->redirectToRoute('oc_platform_home');
    }

    public function categoryAction($category)
    {
        $em = $this->getDoctrine()->getManager();
        $adverts = $em->getRepository('OCPlatformBundle:Advert')->getAdvertWithCategories(array($category));
        
        return $this->render('OCPlatformBundle:Advert:adsByCategory.html.twig', array(
            'adverts' => $adverts
        ));
    }
}

src/OC/PlatformBundle/Resources/views/Advert/add.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/add.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block body %}

    <h2>Ajouter une annonce</h2>

    {{ include("OCPlatformBundle:Advert:form.html.twig") }}

    <p>
        Attention : cette annonce sera ajoutée directement
        sur la page d'accueil après validation du formulaire.
    </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/adsByCategory.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}
    <div>
        {# On affiche tous les messages flash dont le nom est « info » #}
        {% for message in app.session.flashbag.get('notice') %}
            <p class="alert alert-info"> Message flash : {{ message }}</p>
        {% endfor %}
    </div>

    <h2>Liste des annonces</h2>

    <ul>
        {% for advert in adverts %}
        <li>
            <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
            {{ advert.title }}
            </a>
            par {{ advert.author }},
            le {{ advert.date|date('d/m/Y') }}
        </li>
        {% else %}
        <li>Pas (encore !) d'annonces</li>
        {% endfor %}
    </ul>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/categories.html.twig
<ul class="dropdown-menu">
    {% for category in categories %}
        <li class="dropdown-item">
            <a href="{{ path('oc_platform_category', {'category': category.name}) }}">
            {{ category.name }}
            </a>
        </li>
    {% else %}
        <li class="dropdown-item">Pas (encore !) de catégories</li>
    {% endfor %}
</ul>

src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Supprimer une annonce</h2>

    <p>
        Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
    </p>

    <form action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post">
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Retour à l'annonce
        </a>
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {{ form_rest(form) }}
    </form>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Modifier une annonce</h2>

    {{ include("OCPlatformBundle:Advert:form.html.twig") }}

    <p>
        Vous éditez une annonce déjà existante, merci de ne pas changer
        l'esprit général de l'annonce déjà publiée.
    </p>

    <p>
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Retour à l'annonce
        </a>
    </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/form.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/form.html.twig #}

<h3>Formulaire d'annonce</h3>

{# On laisse vide la vue pour l'instant, on la comblera plus tard
lorsqu'on saura afficher un formulaire. #}
<div class="well">
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
    {{ form_errors(form) }}

    {% if form.date is defined %}
        <div class="form-group">
            {{ form_label(form.date, "Date", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
            {{ form_errors(form.date) }}

            <div class="col-sm-2">
            {{ form_widget(form.date.day)}}
            </div>
            <div class="col-sm-2">
            {{ form_widget(form.date.month) }}
            </div>
            <div class="col-sm-2">
            {{ form_widget(form.date.year) }}
            </div>
        </div>
    {% endif %}

    <div class="form-group">
        {{ form_label(form.title, "Titre de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.title) }}

        <div class="col-sm-10">
        {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.content, "Contenu de l'annonce", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.content) }}
        <div class="col-sm-10">
        {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.author, "Auteur", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.author) }}

        <div class="col-sm-10">
        {{ form_widget(form.author, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.authorEmail, "Email", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.authorEmail) }}

        <div class="col-sm-10">
        {{ form_widget(form.authorEmail, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.categories, "Catégories", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.categories) }}
        <div class="col-sm-10">
                {{ form_widget(form.categories)}}
        </div>
    </div>


    <div class="form-group">
        {{ form_label(form.image, "Image", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.image) }}

        <div class="col-sm-10">
                {{ form_errors(form.image.file) }}
                {{ form_widget(form.image.file, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    {% if form.date is defined %}
        {{ form_row(form.published) }}
    {% endif %}
    {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

    {# Génération automatique des champs pas encore écrits.
        Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
        et tous les champs cachés (type « hidden »). #}
    {{ form_rest(form) }}

    {{ form_end(form) }}

</div>

src/OC/PlatformBundle/Resources/views/Advert/index.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/index.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}
    <div>
        {# On affiche tous les messages flash dont le nom est « info » #}
        {% for message in app.session.flashbag.get('info') %}
            <p class="alert alert-info"> Message flash : {{ message }}</p>
        {% endfor %}
    </div>

    <h2>Liste des annonces</h2>

    <ul>
        {% for advert in listAdverts %}
        <li>
            <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
            {{ advert.title }}
            </a>
            par {{ advert.author }},
            le {{ advert.date|date('d/m/Y') }}
        </li>
        {% else %}
        <li>Pas (encore !) d'annonces</li>
        {% endfor %}
    </ul>

    <ul class="pagination">
    {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
    {% for p in range(1, nbPages) %}
        <li{% if p == page %} class="active"{% endif %}>
        <a href="{{ path('oc_platform_home', {'page': p}) }}">{{ p }}</a>
        </li>
    {% endfor %}
    </ul>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig #}

{# Ce template n'hérite de personne,
tout comme le template inclus avec {{ include() }}. #}

<ul class="nav nav-pills nav-stacked">
    {% for advert in listAdverts %}
        <li>
            <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
                {{ advert.title }}
            </a>
        </li>
    {% endfor %}
</ul>

src/OC/PlatformBundle/Resources/views/Advert/view.html.twig
{# src/OC/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <div>
        {# On affiche tous les messages flash dont le nom est « info » #}
        {% for message in app.session.flashbag.get('info') %}
            <p class="alert alert-info"> Message flash : {{ message }}</p>
        {% endfor %}
    </div>


    {% if advert.image is not null %}
        <img src="{{ asset(advert.image.webPath) }}" alt="{{ advert.image.alt }}">
    {% endif %}

    <h2>{{ advert.title }}</h2>

    {% if not advert.categories.empty %}
        <p>
            Catégories de l'annonce :
            {% for category in advert.categories %}
            {{ category.name }}{% if not loop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% endif %}

    <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

    <div class="well">
        {{ advert.content }}
    </div>

    <p>
        <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Retour à la liste
        </a>
        <a href="{{ path('oc_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
        <i class="glyphicon glyphicon-edit"></i>
        Modifier l'annonce
        </a>
        <a href="{{ path('oc_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
        <i class="glyphicon glyphicon-trash"></i>
        Supprimer l'annonce
        </a>
    </p>


    <h2>Applications</h2>

    {% if advert.applications.empty %}
        <p class="well"> {{ 'Aucune application n\'a été soumise pour le moment'  }}</p>
    {% else %}
        {% for application in advert.applications() %}
            <i>Par {{ application.author }}, le {{ application.date|date('d/m/Y') }}</i>
            <p class="well"> {{ application.content }}</p>
        {% endfor %}
    {% endif %}


{% endblock %}